// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IApple_15UFZwd_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IApple_15UFZwd_Proxy_ResilientProxy))]
partial interface IFruit
{
}

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IApple_15UFZwd_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IApple_15UFZwd_Proxy_ResilientProxy))]
partial interface IApple
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IApple_15UFZwd_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IFruit
		, global::IApple
	{
		
		public IApple_15UFZwd_Proxy(IFruit inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		async global::System.Threading.Tasks.Task global::IFruit.EatFruitAsync()
		{
			global::IFruit target = (global::IFruit)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.EatFruitAsync(
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.Task global::IApple.EatAppleAsync()
		{
			global::IApple target = (global::IApple)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.EatAppleAsync(
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
	}
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IApple_15UFZwd_Proxy_ResilientProxy : global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyBase<global::IFruit>
		, global::IFruit
		, global::IApple
	{
		
		public IApple_15UFZwd_Proxy_ResilientProxy(
			global::Microsoft.ServiceHub.Framework.IServiceBroker serviceBroker,
			global::Microsoft.ServiceHub.Framework.ServiceRpcDescriptor serviceDescriptor,
			global::Microsoft.ServiceHub.Framework.ServiceActivationOptions options)
			: base(serviceBroker, serviceDescriptor, options)
		{
		}
		
		global::System.Threading.Tasks.Task global::IFruit.EatFruitAsync()
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					await ((global::IFruit)rental.Proxy).EatFruitAsync().ConfigureAwait(false);
				}
			}
		}
		
		global::System.Threading.Tasks.Task global::IApple.EatAppleAsync()
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					await ((global::IApple)rental.Proxy).EatAppleAsync().ConfigureAwait(false);
				}
			}
		}
	}
}
