// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IPear_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IPear_Proxy_ResilientProxy))]
partial interface IPear
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IPear_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IPear
	{
		
		public IPear_Proxy(IPear inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		async global::System.Threading.Tasks.Task global::IPear.EatPearAsync()
		{
			global::IPear target = (global::IPear)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.EatPearAsync(
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
	}
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IPear_Proxy_ResilientProxy : global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyBase<global::IPear>
		, global::IPear
	{
		
		public IPear_Proxy_ResilientProxy(
			global::Microsoft.ServiceHub.Framework.IServiceBroker serviceBroker,
			global::Microsoft.ServiceHub.Framework.ServiceRpcDescriptor serviceDescriptor,
			global::Microsoft.ServiceHub.Framework.ServiceActivationOptions options)
			: base(serviceBroker, serviceDescriptor, options)
		{
		}
		
		global::System.Threading.Tasks.Task global::IPear.EatPearAsync()
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					await ((global::IPear)rental.Proxy).EatPearAsync().ConfigureAwait(false);
				}
			}
		}
	}
}
