// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpc_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpc_Proxy_ResilientProxy))]
partial interface IMyRpc
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpc_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IMyRpc
	{
		
		public IMyRpc_Proxy(IMyRpc inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		async global::System.Threading.Tasks.Task<global::System.IDisposable> global::IMyRpc.ObserveAsync(global::System.Threading.CancellationToken filterToken, global::System.IObserver<int> observer, object __resilientTarget, object __resilientCancellationToken, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.ObserveAsync(
					filterToken,
					observer,
					__resilientTarget,
					__resilientCancellationToken,
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.ValueTask<global::System.IDisposable> global::IMyRpc.ObserveValueAsync(global::System.IObserver<string> observer, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.ObserveValueAsync(
					observer,
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.Task<global::System.IDisposable> global::IMyRpc.ObserveWithoutCancellationAsync(global::System.IObserver<double> observer)
		{
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.ObserveWithoutCancellationAsync(
					observer
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
	}
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpc_Proxy_ResilientProxy : global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyBase<global::IMyRpc>
		, global::IMyRpc
	{
		
		public IMyRpc_Proxy_ResilientProxy(
			global::Microsoft.ServiceHub.Framework.IServiceBroker serviceBroker,
			global::Microsoft.ServiceHub.Framework.ServiceRpcDescriptor serviceDescriptor,
			global::Microsoft.ServiceHub.Framework.ServiceActivationOptions options)
			: base(serviceBroker, serviceDescriptor, options)
		{
		}
		
		global::System.Threading.Tasks.Task<global::System.IDisposable> global::IMyRpc.ObserveAsync(global::System.Threading.CancellationToken filterToken, global::System.IObserver<int> observer, object __resilientTarget, object __resilientCancellationToken, global::System.Threading.CancellationToken cancellationToken)
		{
			return this.InvokeTaskSubscriptionAsync(__resilientTarget_ => ((global::IMyRpc)__resilientTarget_).ObserveAsync(filterToken, observer, __resilientTarget, __resilientCancellationToken, cancellationToken), (__resilientTarget_, __resilientCancellationToken_) => ((global::IMyRpc)__resilientTarget_).ObserveAsync(filterToken, observer, __resilientTarget, __resilientCancellationToken, __resilientCancellationToken_), cancellationToken);
		}
		
		global::System.Threading.Tasks.ValueTask<global::System.IDisposable> global::IMyRpc.ObserveValueAsync(global::System.IObserver<string> observer, global::System.Threading.CancellationToken cancellationToken)
		{
			return this.InvokeValueTaskSubscriptionAsync(__resilientTarget => ((global::IMyRpc)__resilientTarget).ObserveValueAsync(observer, cancellationToken), (__resilientTarget, __resilientCancellationToken) => ((global::IMyRpc)__resilientTarget).ObserveValueAsync(observer, __resilientCancellationToken), cancellationToken);
		}
		
		global::System.Threading.Tasks.Task<global::System.IDisposable> global::IMyRpc.ObserveWithoutCancellationAsync(global::System.IObserver<double> observer)
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task<global::System.IDisposable> InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					return await ((global::IMyRpc)rental.Proxy).ObserveWithoutCancellationAsync(observer).ConfigureAwait(false);
				}
			}
		}
	}
}
