// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpcWithEvent_Proxy))]
partial interface IMyRpcWithEvent
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpcWithEvent_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IMyRpcWithEvent
	{
		
		public IMyRpcWithEvent_Proxy(IMyRpcWithEvent inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		public event global::System.EventHandler? VanillaEvent
		{
			add
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.VanillaEvent += value;
				}
			}
		
			remove
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.VanillaEvent -= value;
				}
			}
		}
		
		public event global::System.EventHandler<global::MyEventArgs>? MyEvent
		{
			add
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.MyEvent += value;
				}
			}
		
			remove
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.MyEvent -= value;
				}
			}
		}
	}
}
