// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpcWithEvent_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpcWithEvent_Proxy_ResilientProxy))]
partial interface IMyRpcWithEvent
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpcWithEvent_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IMyRpcWithEvent
	{
		
		public IMyRpcWithEvent_Proxy(IMyRpcWithEvent inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		public event global::System.EventHandler? VanillaEvent
		{
			add
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.VanillaEvent += value;
				}
		
			}
		
			remove
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.VanillaEvent -= value;
				}
			}
		}
		
		public event global::System.EventHandler<global::MyEventArgs>? MyEvent
		{
			add
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.MyEvent += value;
				}
		
			}
		
			remove
			{
				if (this.TargetOrNull is global::IMyRpcWithEvent target)
				{
					target.MyEvent -= value;
				}
			}
		}
	}
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpcWithEvent_Proxy_ResilientProxy : global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyBase<global::IMyRpcWithEvent>
		, global::IMyRpcWithEvent
	{
		private readonly ResilientEvent<global::System.EventHandler> VanillaEventSubscription;
		private readonly ResilientEvent<global::System.EventHandler<global::MyEventArgs>> MyEventSubscription;
		
		public IMyRpcWithEvent_Proxy_ResilientProxy(
			global::Microsoft.ServiceHub.Framework.IServiceBroker serviceBroker,
			global::Microsoft.ServiceHub.Framework.ServiceRpcDescriptor serviceDescriptor,
			global::Microsoft.ServiceHub.Framework.ServiceActivationOptions options)
			: base(serviceBroker, serviceDescriptor, options)
		{
			this.VanillaEventSubscription = this.CreateEvent<global::System.EventHandler>(
				(sender, args) => this.VanillaEventSubscription.Handlers?.Invoke(this, args),
				(proxy, handler) => ((global::IMyRpcWithEvent)proxy).VanillaEvent += handler,
				(proxy, handler) => ((global::IMyRpcWithEvent)proxy).VanillaEvent -= handler);
			this.MyEventSubscription = this.CreateEvent<global::System.EventHandler<global::MyEventArgs>>(
				(sender, args) => this.MyEventSubscription.Handlers?.Invoke(this, args),
				(proxy, handler) => ((global::IMyRpcWithEvent)proxy).MyEvent += handler,
				(proxy, handler) => ((global::IMyRpcWithEvent)proxy).MyEvent -= handler);
		}
		
		public event global::System.EventHandler? VanillaEvent
		{
			add
			{
				this.VanillaEventSubscription.UpdateHandlers(value, add: true);
			}
		
			remove
			{
				this.VanillaEventSubscription.UpdateHandlers(value, add: false);
			}
		}
		
		public event global::System.EventHandler<global::MyEventArgs>? MyEvent
		{
			add
			{
				this.MyEventSubscription.UpdateHandlers(value, add: true);
			}
		
			remove
			{
				this.MyEventSubscription.UpdateHandlers(value, add: false);
			}
		}
	}
}
