compressionLevel: mixed

enableGlobalCache: false

npmRegistryServer: "https://pkgs.dev.azure.com/azure-public/vside/_packaging/msft_consumption/npm/registry/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
