packages:
  - .

allowBuilds:
  unrs-resolver: true
overrides:
  '@babel/code-frame': 7.29.0
  '@babel/compat-data': 7.29.3
  '@babel/core': 7.29.6
  '@babel/generator': 7.29.6
  '@babel/helper-compilation-targets': 7.28.6
  '@babel/helper-globals': 7.28.0
  '@babel/helper-module-imports': 7.28.6
  '@babel/helper-module-transforms': 7.28.6
  '@babel/helper-plugin-utils': 7.28.6
  '@babel/helper-string-parser': 7.27.1
  '@babel/helper-validator-identifier': 7.28.5
  '@babel/helper-validator-option': 7.27.1
  '@babel/helpers': 7.29.2
  '@babel/parser': 7.29.3
  '@babel/plugin-syntax-import-attributes': 7.28.6
  '@babel/plugin-syntax-jsx': 7.28.6
  '@babel/plugin-syntax-typescript': 7.28.6
  '@babel/template': 7.28.6
  '@babel/traverse': 7.29.0
  '@babel/types': 7.29.0
  '@humanfs/core': 0.19.1
  '@humanfs/node': 0.16.7
  synckit: 0.11.12
  unrs-resolver: 1.11.1
