packages:
  - .
virtualStoreDir: ../../obj/servicebroker-npm-pnpm

allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - baseline-browser-mapping
  - caniuse-lite
  - electron-to-chromium
  - lru-cache
  - node-releases
overrides:
  '@babel/code-frame': 7.29.0
  '@babel/compat-data': 7.29.0
  '@babel/core': 7.29.0
  '@babel/generator': 7.29.1
  '@babel/helper-compilation-targets': 7.28.6
  '@babel/helper-globals': 7.28.0
  '@babel/helper-module-imports': 7.28.6
  '@babel/helper-module-transforms': 7.28.6
  '@babel/helper-plugin-utils': 7.28.6
  '@babel/helper-string-parser': 7.27.1
  '@babel/helper-validator-identifier': 7.28.5
  '@babel/helper-validator-option': 7.27.1
  '@babel/helpers': 7.28.6
  '@babel/parser': 7.29.0
  '@babel/plugin-syntax-import-attributes': 7.28.6
  '@babel/plugin-syntax-jsx': 7.28.6
  '@babel/plugin-syntax-typescript': 7.28.6
  '@babel/template': 7.28.6
  '@babel/traverse': 7.29.0
  '@babel/types': 7.29.0
  '@istanbuljs/schema': 0.1.3
  '@pkgr/core': 0.2.9
  '@sinclair/typebox': 0.34.48
  '@types/estree': 1.0.8
  '@ungap/structured-clone': 1.3.0
  '@humanfs/core': 0.19.1
  '@humanfs/node': 0.16.7
  acorn: 8.16.0
  ajv: 6.14.0
  baseline-browser-mapping: 2.10.32
  'brace-expansion@1': 1.1.14
  'brace-expansion@2': 2.1.0
  'brace-expansion@5': 5.0.5
  browserslist: 4.28.1
  caniuse-lite: 1.0.30001790
  electron-to-chromium: 1.5.367
  get-east-asian-width: 1.5.0
  immutable: 5.1.4
  istanbul-lib-processinfo: 3.0.0
  'lru-cache@11': 11.3.4
  node-releases: 2.0.38
  'picomatch@4': 4.0.3
  react-is: 19.2.6
  react-is-19: npm:react-is@19.2.6
  synckit: 0.11.12
  tinyglobby: 0.2.15
  unrs-resolver: 1.11.1
