// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

partial class OuterClass
{
	[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.OuterClass_IMyRpc_Proxy))]
	partial interface IMyRpc
	{
	}
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class OuterClass_IMyRpc_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::OuterClass.IMyRpc
	{
		
		public OuterClass_IMyRpc_Proxy(OuterClass.IMyRpc inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		async global::System.Threading.Tasks.Task global::OuterClass.IMyRpc.JustCancellationAsync(global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::OuterClass.IMyRpc target = (global::OuterClass.IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.JustCancellationAsync(
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
	}
}
