// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpc_Proxy))]
[global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpc_Proxy_ResilientProxy))]
partial interface IMyRpc
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpc_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IMyRpc
	{
		
		public IMyRpc_Proxy(IMyRpc inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		async global::System.Threading.Tasks.Task global::IMyRpc.JustCancellationAsync(global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.JustCancellationAsync(
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.ValueTask global::IMyRpc.AnArgAndCancellationAsync(int arg, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				await target.AnArgAndCancellationAsync(
					arg,
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.ValueTask<int> global::IMyRpc.NoArgsOrCancellation()
		{
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.NoArgsOrCancellation(
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.Task<int> global::IMyRpc.AddAsync(int a, int b, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.AddAsync(
					a,
					b,
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		async global::System.Threading.Tasks.Task<int> global::IMyRpc.MultiplyAsync(int a, int b)
		{
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return await target.MultiplyAsync(
					a,
					b
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		void global::IMyRpc.Start(string bah)
		{
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				target.Start(
					bah
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		void global::IMyRpc.StartCancelable(string bah, global::System.Threading.CancellationToken token)
		{
			token.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				target.StartCancelable(
					bah,
					token
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
		
		global::System.Collections.Generic.IAsyncEnumerable<int> global::IMyRpc.CountAsync(int start, int count, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			global::IMyRpc target = (global::IMyRpc)this.Target;
			if (target is null) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			try
			{
				return target.CountAsync(
					start,
					count,
					cancellationToken
					);
			}
			catch (global::System.Exception ex)
			{
				throw this.ExceptionHelper(ex);
			}
		}
	}
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpc_Proxy_ResilientProxy : global::Microsoft.ServiceHub.Framework.Reflection.ResilientProxyBase<global::IMyRpc>
		, global::IMyRpc
	{
		
		public IMyRpc_Proxy_ResilientProxy(
			global::Microsoft.ServiceHub.Framework.IServiceBroker serviceBroker,
			global::Microsoft.ServiceHub.Framework.ServiceRpcDescriptor serviceDescriptor,
			global::Microsoft.ServiceHub.Framework.ServiceActivationOptions options)
			: base(serviceBroker, serviceDescriptor, options)
		{
		}
		
		global::System.Threading.Tasks.Task global::IMyRpc.JustCancellationAsync(global::System.Threading.CancellationToken cancellationToken)
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task InvokeAsync()
			{
				cancellationToken.ThrowIfCancellationRequested();
				using (ProxyRental rental = await this.RentProxyAsync(cancellationToken).ConfigureAwait(false))
				{
					await ((global::IMyRpc)rental.Proxy).JustCancellationAsync(cancellationToken).ConfigureAwait(false);
				}
			}
		}
		
		global::System.Threading.Tasks.ValueTask global::IMyRpc.AnArgAndCancellationAsync(int arg, global::System.Threading.CancellationToken cancellationToken)
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.ValueTask InvokeAsync()
			{
				cancellationToken.ThrowIfCancellationRequested();
				using (ProxyRental rental = await this.RentProxyAsync(cancellationToken).ConfigureAwait(false))
				{
					await ((global::IMyRpc)rental.Proxy).AnArgAndCancellationAsync(arg, cancellationToken).ConfigureAwait(false);
				}
			}
		}
		
		global::System.Threading.Tasks.ValueTask<int> global::IMyRpc.NoArgsOrCancellation()
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.ValueTask<int> InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					return await ((global::IMyRpc)rental.Proxy).NoArgsOrCancellation().ConfigureAwait(false);
				}
			}
		}
		
		global::System.Threading.Tasks.Task<int> global::IMyRpc.AddAsync(int a, int b, global::System.Threading.CancellationToken cancellationToken)
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task<int> InvokeAsync()
			{
				cancellationToken.ThrowIfCancellationRequested();
				using (ProxyRental rental = await this.RentProxyAsync(cancellationToken).ConfigureAwait(false))
				{
					return await ((global::IMyRpc)rental.Proxy).AddAsync(a, b, cancellationToken).ConfigureAwait(false);
				}
			}
		}
		
		global::System.Threading.Tasks.Task<int> global::IMyRpc.MultiplyAsync(int a, int b)
		{
			return InvokeAsync();
			
			async global::System.Threading.Tasks.Task<int> InvokeAsync()
			{
				using (ProxyRental rental = await this.RentProxyAsync(default).ConfigureAwait(false))
				{
					return await ((global::IMyRpc)rental.Proxy).MultiplyAsync(a, b).ConfigureAwait(false);
				}
			}
		}
		
		void global::IMyRpc.Start(string bah)
		{
			this.InvokeNotification(target => ((global::IMyRpc)target).Start(bah), default);
		}
		
		void global::IMyRpc.StartCancelable(string bah, global::System.Threading.CancellationToken token)
		{
			token.ThrowIfCancellationRequested();
			this.InvokeNotification(target => ((global::IMyRpc)target).StartCancelable(bah, token), token);
		}
		
		global::System.Collections.Generic.IAsyncEnumerable<int> global::IMyRpc.CountAsync(int start, int count, global::System.Threading.CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			return this.InvokeAsyncEnumerableAsync(target => ((global::IMyRpc)target).CountAsync(start, count, cancellationToken), cancellationToken);
		}
	}
}
