//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceHub.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceHub.Analyzers.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This typically takes the form of &quot;({0} as IDisposable)?.Dispose();&quot;. Be sure to do this within a finally block that ensures the proxy is disposed of even in exceptional cases..
        /// </summary>
        internal static string ISB001_DisposeOfAcquiredProxy_Description {
            get {
                return ResourceManager.GetString("ISB001_DisposeOfAcquiredProxy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always dispose of proxies..
        /// </summary>
        internal static string ISB001_DisposeOfAcquiredProxy_MessageFormat {
            get {
                return ResourceManager.GetString("ISB001_DisposeOfAcquiredProxy_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This typically takes the form of &quot;({0} as IDisposable)?.Dispose();&quot;.
        /// </summary>
        internal static string ISB001_DisposeOfProxyBeforeReplacingReference_Description {
            get {
                return ResourceManager.GetString("ISB001_DisposeOfProxyBeforeReplacingReference_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose of old proxy before overwriting reference to it..
        /// </summary>
        internal static string ISB001_DisposeOfProxyBeforeReplacingReference_MessageFormat {
            get {
                return ResourceManager.GetString("ISB001_DisposeOfProxyBeforeReplacingReference_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy stored in &quot;{0}.{1}&quot; must be disposed by an IDisposable.Dispose or Dispose(bool) method on the &quot;{0}&quot; type..
        /// </summary>
        internal static string ISB001_ProxyMemberMustBeDisposedInDisposeMethod_MessageFormat {
            get {
                return ResourceManager.GetString("ISB001_ProxyMemberMustBeDisposedInDisposeMethod_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose of proxies.
        /// </summary>
        internal static string ISB001_Title {
            get {
                return ResourceManager.GetString("ISB001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use rentals as a local variable inside an async method and dispose the rental when done. If you need to store proxies for longer than the duration of an async method, use IServiceBroker instead..
        /// </summary>
        internal static string ISB002_Description {
            get {
                return ResourceManager.GetString("ISB002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid storing ServiceBrokerClient.Rental&lt;T&gt; in a field or property..
        /// </summary>
        internal static string ISB002_MessageFormat {
            get {
                return ResourceManager.GetString("ISB002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid storing rentals in fields.
        /// </summary>
        internal static string ISB002_Title {
            get {
                return ResourceManager.GetString("ISB002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes attributed with ExportBrokeredServiceAttribute must implement IExportedBrokeredService..
        /// </summary>
        internal static string ISB003_Description {
            get {
                return ResourceManager.GetString("ISB003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; must implement IExportedBrokeredService..
        /// </summary>
        internal static string ISB003_MessageFormat {
            get {
                return ResourceManager.GetString("ISB003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported brokered service validity.
        /// </summary>
        internal static string ISB003_Title {
            get {
                return ResourceManager.GetString("ISB003_Title", resourceCulture);
            }
        }
    }
}
