// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::Microsoft.ServiceHub.Framework.Reflection.LocalProxyMappingAttribute(typeof(Microsoft.ServiceHub.Framework.Generated.IMyRpc_Proxy))]
partial interface IMyRpc
{
}

namespace Microsoft.ServiceHub.Framework.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.ServiceHub.Analyzers.CSharp", "x.x.x.x")]
	internal class IMyRpc_Proxy : global::Microsoft.ServiceHub.Framework.Reflection.ProxyBase
		, global::IMyRpc
	{
		
		public IMyRpc_Proxy(IMyRpc inner, in global::Microsoft.ServiceHub.Framework.Reflection.ProxyInputs inputs)
			: base(inner, inputs)
		{
		}
		
		public event global::CustomEventHandler? Changed
		{
			add
			{
				if (this.TargetOrNull is global::IMyRpc target)
				{
					target.Changed += value;
				}
		
			}
		
			remove
			{
				if (this.TargetOrNull is global::IMyRpc target)
				{
					target.Changed -= value;
				}
			}
		}
	}
}
