parameters:
  RunTests:

steps:

- script: pnpm test
  displayName: 🧪 pnpm test
  workingDirectory: src/servicebroker-npm
  condition: and(succeeded(), ${{ parameters.RunTests }})

- powershell: src/servicebroker-npm/pack.ps1
  displayName: 📦 pnpm pack
